// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.20.3
// source: protos/common/decimal.proto

package gopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decimal is an internal type that allows for transferring information to and from an exact Decimal
// value, so that it can be sent over the wire between processes
type Decimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parts []int64 `protobuf:"varint,1,rep,packed,name=parts,proto3" json:"parts,omitempty"` // Base value containing all the digits of data as a single number (i.e. to store -123.45 this value should be -12345)
	Exp   int32   `protobuf:"varint,2,opt,name=exp,proto3" json:"exp,omitempty"`            // Exponent to shift the value (i.e. to store -123.45 this value should be -2)
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_common_decimal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_decimal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_protos_common_decimal_proto_rawDescGZIP(), []int{0}
}

func (x *Decimal) GetParts() []int64 {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Decimal) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

var File_protos_common_decimal_proto protoreflect.FileDescriptor

var file_protos_common_decimal_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x31, 0x0a, 0x07,
	0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x78, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x78, 0x65,
	0x66, 0x69, 0x6e, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x65,
	0x6e, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_common_decimal_proto_rawDescOnce sync.Once
	file_protos_common_decimal_proto_rawDescData = file_protos_common_decimal_proto_rawDesc
)

func file_protos_common_decimal_proto_rawDescGZIP() []byte {
	file_protos_common_decimal_proto_rawDescOnce.Do(func() {
		file_protos_common_decimal_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_common_decimal_proto_rawDescData)
	})
	return file_protos_common_decimal_proto_rawDescData
}

var file_protos_common_decimal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_common_decimal_proto_goTypes = []interface{}{
	(*Decimal)(nil), // 0: protos.common.Decimal
}
var file_protos_common_decimal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_common_decimal_proto_init() }
func file_protos_common_decimal_proto_init() {
	if File_protos_common_decimal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_common_decimal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_common_decimal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_common_decimal_proto_goTypes,
		DependencyIndexes: file_protos_common_decimal_proto_depIdxs,
		MessageInfos:      file_protos_common_decimal_proto_msgTypes,
	}.Build()
	File_protos_common_decimal_proto = out.File
	file_protos_common_decimal_proto_rawDesc = nil
	file_protos_common_decimal_proto_goTypes = nil
	file_protos_common_decimal_proto_depIdxs = nil
}
